version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ag-prueba-front"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "maven"
    directory: "/authorization-server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "maven"
    directory: "/resource-server"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
