name: CD

on:
  push:
    branches: [develop]   # despliegue automático al hacer push en main
  workflow_dispatch:   # también puedes lanzarlo manualmente

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build Angular app
        run: |
          cd ag-prueba-front
          npm ci
          npm run build --if-present
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ag-prueba-front/dist/ag-prueba-front
