name: CI

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  shared-setup:
    uses: ./.github/workflows/shared.yml
    with:
      node_version: '20'
      java_version: '17'
      deploy_env: 'ci'

  frontend:
    needs: shared-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
        working-directory: ag-prueba-front
      - name: Lint
        run: npm run lint --if-present
        working-directory: ag-prueba-front
      - name: Build
        run: npm run build --if-present
        working-directory: ag-prueba-front

  authorization-server:
    needs: shared-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & Package (skip tests)
        run: mvn -B clean package -DskipTests
        working-directory: authorization-server

  resource-server:
    needs: shared-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & Package (skip tests)
        run: mvn -B clean package -DskipTests
        working-directory: resource-server
